#version 450

// ------------------------------------------------------------------
// DEFINES ----------------------------------------------------------
// ------------------------------------------------------------------

#define NUM_THREADS_X 8
#define NUM_THREADS_Y 8

// ------------------------------------------------------------------
// INPUTS -----------------------------------------------------------
// ------------------------------------------------------------------

layout(local_size_x = NUM_THREADS_X, local_size_y = NUM_THREADS_Y, local_size_z = 1) in;

// ------------------------------------------------------------------
// DESCRIPTOR SETS --------------------------------------------------
// ------------------------------------------------------------------

// Current Reprojection Write DS
layout(set = 0, binding = 0, rg16f) uniform writeonly image2D i_Output;

layout(set = 1, binding = 2, std430) buffer UniformTileData_t
{
    ivec4 coord_and_value[];
}
UniformTileData;

// ------------------------------------------------------------------
// MAIN -------------------------------------------------------------
// ------------------------------------------------------------------

void main()
{
    ivec4 data  = UniformTileData.coord_and_value[gl_WorkGroupID.x];
    ivec2 coord = data.xy + ivec2(gl_LocalInvocationID.xy);
    float value = intBitsToFloat(data.z);

    imageStore(i_Output, coord, vec4(value, 0.0f, 0.0f, 0.0f));
}

// ------------------------------------------------------------------